config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  # get 'blogs/index'
  # get 'blogs/show'
  # get 'blogs/new'
  # get 'blogs/edit'

  resources :blogs

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "blogs#index"
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :category, :dependent => :destroy

    has_one_attached :image 

    has_rich_text :content

    def self.ransackable_attributes(auth_object = nil)
        ["title"]
    end

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @q = Blog.ransack(params[:q])
    @blogs = @q.result(distinct: true)
    @blogs = Blog.all if @q.result.none?

     # Check if category filter parameter is present
     if params[:cate].present?
      @blogs = @blogs.where(category_id: params[:cate])
    end

    # Paginate the filtered blogs
    @pagy, @blogs = pagy(@blogs)

    # Retrieve all categories for the sidebar
    @categories = Category.all

  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.create(blog_params)

    if @blog.save
      redirect_to @blog
    else
      render :new
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    
    if @blog.update(blog_params)
      redirect_to @blog
    else
      render :edit
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice: 'Blog was successfully destroyed.'
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content, :category_id, :image)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blogs/_form.html.erb
<div class="flex-row d-flex justify-content-center">
    <div class="col-md-8">
        <div class="card mt-5">
            <div class="card-body">
                <%= form_for @blog do |f| %>

                    <div class="form-group">
                        <%= f.label :title %>
                        <%= f.text_field :title, class: 'form-control' %>
                    </div>
                
                    <div class="form-group mt-2">
                        <%= f.label :content %>
                        <%= f.rich_text_area :content, class: 'form-control customized-min-height', style:"height: 150px;" %>
                    </div>

                    <div class="form-group mt-2">
                        <%= f.label :image %>
                        <%= f.file_field :image, class: 'form-control' %>
                    </div>
            
                    <div class="form-group mt-3">
                        <%= f.select :category_id, Category.all.map {|c| [c.category, c.id]} %>
                    </div>

                    <%= f.submit "Create Blog", class: 'btn btn-primary mt-3' %>
                    <%= link_to "Back", blogs_path, class: 'btn btn-light mt-3' %>
                
                <% end %>
            </div>
        </div>
    </div>
</div>

<style>
    select{
        width: 300px;
        height: 30px;
    }
</style>

app/views/blogs/edit.html.erb
<%= render "form" %>

app/views/blogs/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="row">
            <% @blogs.each do |blog| %>
                <div class="col-md-6">
                <div class="card mt-3">
                    <div class="card-body">
                        <h4> <%= link_to blog.title, blog_path(blog.id) %> </h4>
                        <% if blog.image.attached? %>
                            <%= image_tag(blog.image) %>
                        <% end %>
                        <% if user_signed_in? %>
                            <%= link_to "View", blog_path(blog.id), class: 'btn btn-primary mt-2' %>
                            <%= link_to "Delete", blog_path(blog.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger mt-2" %>
                        <% else %>
                        <%= link_to new_user_session_path, class: 'nav-link' do %>
                            <p class="btn btn-primary mt-2"> Login to view blog</p>
                        <% end %>
                        <% end %>
                    </div>
                </div>
                </div>
            <% end %>
            </div>
        </div>

        <div class="col-md-4 mt-3 order-mobile-first">
            <%= search_form_for @q, html: { class: "d-flex" } do |f| %>
                <div class="input-group me-3">
                <%= f.text_field :title_cont, class: "form-control", placeholder: "Search by title" %>
                <button type="submit" class="btn btn-primary search1">Search</button>
                </div>
            <% end %>
            <div class="card mt-3">
                <div class="card-header">
                    Categories
                </div>
                <div class="card-body">
                    <ul class="list-group">
                    <% @categories.each do |category| %>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <%= link_to category.category, blogs_path(:cate => category.id) %>
                            <span> <%= category.blogs.count %></span>
                        </li>
                    <% end %>   
                    </ul>
                </div>
            </div>
        </div>
         
        <div class="page mt-5">
            <%== pagy_bootstrap_nav(@pagy) %>
         </div>               
    </div>
</div>


<style>
    a{
        text-decoration: none;
        color: #fff;
    }
    img{
        width: 370px;
        height: 230px;
        border-radius: 5px;
    }
    @media screen and (max-width: 1025px) {
        img {
            height: 170px!important;
            width: 270px;
        }
    }
    @media screen and (max-width: 770px) {
        img {
            height: 120px!important;
            width: 195px;
        }
    }
    @media screen and (max-width: 430px) {
        img {
            height: 230px!important;
            width: 370px;
        }
    }
    @media screen and (max-width: 380px) {
        img {
            height: 200px!important;
            width: 330px;
        }
    }
    @media screen and (max-width: 325px) {
        img {
            height: 170px!important;
            width: 275px;
        }
    }

    @media screen and (max-width: 767px) {
        .order-mobile-first {
            order: -1; 
        }

        .order-mobile-second {
            order: 1; 
        }
    }
    
</style>

app/views/blogs/new.html.erb
<%= render "form" %>

app/views/blogs/show.html.erb
<div class="flex-row d-flex justify-content-center mb-5">
    <div class="col-md-8">
    <div class="card mt-5">
            <div class="card-body">
<h1><%= @blog.title %></h1>

<h3>Category: <%= @blog.category.category %> </h3>

<div class="text-center">
<% if @blog.image.attached? %>
    <%= image_tag(@blog.image, class: "img-fluid", style:"max-height: 300px;") %>
<% end %>
</div>

<p><%= @blog.content %></p>

<div style="float: right;">
<%= link_to "Edit", edit_blog_path(@blog.id), class: 'btn btn-primary' %>
<%= link_to "Delete", blog_path(@blog), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
<%= link_to "Back", blogs_path, class: 'btn btn-light' %>
</div

</div>
</div>

</div>
</div>

<style>
    h1{
        text-align: center
    }
    h3{
        text-align: center
    }
    p{
        text-align: justify
    }
</style>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Category:</strong>
    <%= category.category %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "style", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'trix' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand"><%= link_to "BlogApp", blogs_path, class: 'nav-link', style:"color: #473a5e;" %></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto">
            <% if user_signed_in? %>
              <li class="nav-item active">
                <%= link_to "Create Blog", new_blog_path, class: 'nav-link' %>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="far fa-user"></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <li><%= link_to 'Edit Profile', edit_user_registration_path, class: 'dropdown-item' %></li>
                  <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %></li>
                </ul>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: 'nav-link' do %>
                  <i class="fas fa-user"></i>
                <% end %>
              </li>
            <% end %>
          </ul>
          
        </div>
      </div>
    </nav>

    <p class="notice" style="text-align:center; color: green;"><%= notice %></p>
    <p class="alert" style="text-align:center; color: red;"><%= alert %></p>

    <%= yield %>
  </body>
</html>